### ISSUE TITLE
small amounts of unwanted items in trains

### ISSUE THREAD

**Issue by Opiboble** [Yousei9/Factorio-LogisticTrainNetwork#11] opened 2017-03-16 06:44 UTC
Hello,

I have ran into a rather small issue with some deliveries, and that is that once in a blue moon a small amount of cargo gets left in the car. Not sure how, but it does, and again this isn't a huge issue since most if not all my stops use filter inserts to unload. But here comes the change I would love to see... Instead of waiting for (example) "Cargo: Iron plate = 0", change it to "Empty Cargo Inventory". This way when it eventually goes to a station needing those random items, but is delivering something else (I lean on having multiple items delivered to a single requesting station) it will wait till they are pulled. I know it is a random issue, but I have not found any work arounds to the problem as of yet. Anyway thanks for the great mod! It is making my train network awesome! No trains not working : )

**Comment by Yousei9** [comment] 2017-03-16 07:26
It happens almost always at stations providing more than 1 item. The reason behind it: Inserters are stupid. They try to insert items into full wagons, can't fit it in and keep holding on to items until the next train arrives.

Your suggestion would result in either requesters filling up with items they don't want or trains getting stuck trying to get a full load of iron when a single copper is preventing that.

Here's some working solutions:

1) add inserters able to unload unwanted items. It does take a bit more complicated designs, especially if you don't always load wagons full and instead have 20 stacks iron 15 stacks copper.
Best solution, trains still can't cant stuck at loading stations anymore.

2) Always empty trains at depots and set up a high priority provider to distribute those excess items back into the network.
I'm using it alongside 1) just to be safe.

3) Inserters can be forced to load specific number of items from belts. Loading will be several times slower than any other method.

4) There's a mod turning inserters 180° if they are stuck with items, but it takes quite some cpu time.

5) wait for 0.15. Devs have confirmed inserters will get controllable pickup size. (Send 5 copper and it will pick up 5 instead of a full stack)

**Comment by Opiboble** [comment] 2017-03-16 07:42
Ah, if they are solving this in 0.15 I will wait. Until then I think I will implement #2 by moving my refueling area to near my trash items sorting area. thank you for the tip : )

**Comment by Smileynator** [comment] 2017-04-13 19:34
Wouldn't the temp workaround be to make the mod never allocate a full train? (use all but 1 slot or something) so that overflow never happens?
Otherwise, make the player decide with a "max delivery request/size" addition. So you can limit the request 1 train might do at once/per wagon?

**Comment by Yousei9** [comment] 2017-04-22 09:16
Update 1.1.0:
Preventing inserters ending up holding items and inserting them into the next train became much easier.
1. By default trains will only leave after all inserters stopped loading.
2. Setting "Locked Slots per Wagon" to 1/ item in merged delivery will leave room for inserters to start new stacks.

This removed the necessity for inserters unloading unwanted items in my test scenarios.

**Comment by Opiboble** [comment] 2017-04-24 21:35
Awesome! Thank you very much! No more need for a railcar trash system!

**Closed** 2017-05-31 05:11 UTC
Labels: question
