### ISSUE TITLE
Fluid unloading incomplete due to rounding error

### ISSUE THREAD

**Issue by Leucetius** [Yousei9/Factorio-LogisticTrainNetwork#31] opened 2017-05-15 07:17 UTC
Due to the rounding behaviour of vanilla combined with fluidcount times 10 since 0.15 it happens quite often that a fluid train leaves its unloading station with a small residue (about 0.2 - 0.5) still in its car.
In my case reducing the possible load capacity by factor 2 because the LCCL train alternates between two different sources (gas and oil). This leads to 1 car not being usable at either station because it has a small amount of the other fluid in it.

My crude fix for now: control.lua, line 687, insert in front of "if finish_loading then":

if countOverride == 0 then --unload
  record.wait_conditions[#record.wait_conditions+1] = {type = "inactivity", compare_type = "and", ticks = 60 } --wait 1 second, probably 30 ticks are enough, 15 were not
end

Effectively the same as "finish_loading" but for unloading only.

**Comment by Yousei9** [comment] 2017-05-15 07:29
Residue in fluid wagons is classified as not a bug by the devs.
Their reply simply is to use 3 pumps for unloading.

Use 3 pumps and leave finish loading active and this is not an issue.

**Comment by Yousei9** [comment] 2017-05-31 07:53
The more I look into the issue the more it feels like this is a bug that should be fixed in the game by rounding up fluid wagon contents.
https://forums.factorio.com/viewtopic.php?f=23&t=47626&p=283762#p283762

**Closed** 2017-06-02 05:26 UTC
Labels: bug
